### ISSUE TITLE
[Model] Baseline 코드 구축 및 실험

### ISSUE THREAD

**Issue by jeongjae96** [updaun/TVControlHandGestureRecognition#3]
### Todo
- [x] 베이스라인 프로젝트 환경에 맞게 구축
- [x] 개발 용이성을 위한 OOP 설계
  - [ ] 리팩터링
  - [ ] 모델 저장 기능 추가
  - [ ] 로깅 기능 추가 
- 베이스라인 모델을 통한 실험
  - [ ] 틀리는 검증 데이터에 대한 분석
